### ISSUE TITLE
Weird Issue

### ISSUE THREAD

**Issue by bladefist** [kamranayub/GiantBomb-CSharp#13]
I had a weird issue where nothing would work in my project, but other projects worked fine. I don't know what I did, or how I did it, but changing this:

Resource = resource + "/{ResourceId}-{Id}//",

to

Resource = resource + "/{ResourceId}-{Id}/",  

In the main core file under GetSingleResource fixed everything. Any thoughts?

**Comment by kamranayub** [comment]
This was due to GiantBomb-CSharp referencing an out-of-date version of RestSharp. I updated it to reference the latest version which fixes this bug. Thanks!
