### ISSUE TITLE
Filtering results & abstracting pagination

### ISSUE THREAD

**Issue by markadrake** [kamranayub/GiantBomb-CSharp#22]
> Request the "games" resource, filtered by date_last_updated, and pull back all results if pagination exists.

How do you accomplish this task within the API? As an example, you could put your own key in the following URL to pull back the first page of anything updated in the last year.

http://www.giantbomb.com/api/games/?api_key=**{YOUR_API_KEY}**&filter=date_last_updated:2015-10-1%2000:00:00|2017-1-1%2000:00:00

I saw the note on the wiki about adding a filter to the releases object. This code doesn't seem to work for releases, nor games. It could be a problem with my code or my implementation.

Thanks!

**Comment by kamranayub** [comment]
Let me do some testing to try and see if it's a problem with the API or something, I'll probably have time this weekend. It seems like something like that should work, if it doesn't. Perhaps try different date time formats? That would be my first avenue.
