### ISSUE TITLE
How does one use Filters?

### ISSUE THREAD

**Issue by FaithLV** [kamranayub/GiantBomb-CSharp#23]
I've been trying for couple of hours, with no success.
I'm trying to get the first game in querry which is a PlayStation 2 game.
Quite new to C#, so I may just be completely incompetent.

Here's the best I got, but it's not quite it.

```
//the ps2 filter
var PlatformFilter = new Dictionary<string, object>() { { "platform", "PlayStation 2" } };

//getting the first game in list
FinalGame = giantBomb.GetGame(resultGame.First(filter: PlatformFilter).Id);
```

Thanks.

**Comment by kamranayub** [comment]
I'm a little confused by what you want. What you're doing now is C# specific, not specific to the SDK. The filtering you're doing right now doesn't filter on GiantBomb so you'll probably run into problems if the list of games doesn't include what you expect.

If all you're asking is how to use LINQ to filter a list, see https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/basic-linq-query-operations

If you actually want the API call to return a filtered list, you have to use Search or the GetGames call and pass in a filter dictionary like you have, except platform should be the ID, not name of the platform.

**Comment by FaithLV** [comment]
Thanks, I was confused (half a year ago) and I did later find out how to do that.

**Comment by kamranayub** [comment]
Yeah I figured you got it, sorry for the delayed response!!
